name: Playwright Tests with Typescript

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  playwright:
    timeout-minutes: 60
    name: "Playwright Tests"
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Node.js (match local version)
      - uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: "npm"

      # Install project dependencies
      - name: Install dependencies
        run: |
          npm ci
          npm install dotenv

      # Install system dependencies for Chromium/Chrome (Ubuntu)
      - name: Install Chromium and OS dependencies
        run: npx playwright install --with-deps chromium

      # Run Playwright tests (logged-in user project)
      - name: Run Playwright tests
        run: npx playwright test

      # Upload HTML report artifact
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 5
